# Файл для пользовательских правил WAF (Задание 2)
# Пример синтаксиса:
# SecRule REQUEST_HEADERS:User-Agent "@contains вредоносный_агент" "id:10000,phase:1,deny,status:403,msg:'Blocked Custom Scanner'"