# RATE LIMITING (Задание 3)
# Раскоментируйте и настройте директиву limit_req_zone ниже:
# limit_req_zone $binary_remote_addr zone=mylimit:10m rate=...;

server {
    listen 80;
    server_name localhost;

    location / {
        # Применение RATE LIMITING (Задание 3)
        # Раскоментируйте и настройте директиву limit_req ниже:
        # limit_req zone=mylimit burst=... nodelay;

        proxy_pass ${BACKEND};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}