services:
  waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
    environment:
      # Проксование трафика на бэкенд
      - BACKEND=http://backend:5000
      # ModSecurity
      - MODSEC_RULE_ENGINE=On
    volumes:
      # Пользовательский конфиг Nginx для настройки Rate Limiting
      - ./nginx/user_nginx.conf:/etc/nginx/templates/conf.d/default.conf.template
      # Файл для пользовательских правил WAF
      - ./nginx/custom.conf:/etc/modsecurity.d/owasp-crs/rules/custom.conf
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"